config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def add
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
    redirect_to flat_path(@flat.id)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end

    redirect_to flat_path(@flat.id)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class ="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our flats</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="col">
        <p>You searched for...</p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <% @flats.each do |flat| %>
      <div class="col-sm-12 col-lg-4">

          <div class="flat-card">


            <div class="flat-card-img" style="background-image: url('https://source.unsplash.com/random/1200x800')">
            </div>

            <div class="flat-card-content">
              <div class="flat-card-title">
                <h4><%= flat.name %></h4>
              </div>
              <p> <%= flat.address %> </p>
              <div class="flex">
                <div class="flex">
                  <h6> <%= flat.number_of_guests %> </h6>
                </div>
                <div class="flex ml-3">
                  <h6> <%= flat.price_per_night %> </h6>
                </div>
              </div>
            </div>

            <div class="flat-card-actions d-flex justify-content-around">
              <a href="<%flat_path(flat.id)%>" class="href">More Information</a>
              <a href="<%edit_flat_path(flat.id)%>" class="href">Edit</a>
            </div>

          </div>
          </div>
          <% end %>

    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('https://source.unsplash.com/random/1200x800')"></div>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"> <%= @flat.address %> </p>
      </div>
      <div class="flat-show-card">
        <h1>Information about the flat:</h1>
        <p> <%= @flat.description %> </p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="flat-show-card">
        <h5> Book this place! </h5>
        <form action>
          <div class="input-group">

          </div>
          <div class="input-group mt-2">

          </div>
          <button class="submit"></button>
        </form>
      </div>
      <div class="flat-show-card">
        <h3> Details </h3>
      </div>
      <div class="flat-show-card">
        <h5> Share </h5>
        <i class ="fa fa-facebook-square fa-2x mr-2"></i>
        <i class ="fa fa-twitter-square fa-2x mr-2"></i>
        <i class ="fa fa-pinterest-square fa-2x mr-2"></i>
        <i class ="fa fa-envelope-square fa-2x mr-2"></i>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a href="/" class="navbar-brand"></a>
      <div class="navbar-items">
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>